site_name: Data Platform Tutorial
site_description: A tutorial on building a data platform, focusing on the different components and how they interact. Each document will be a small step forward in the process, with the goal of building a complete data platform.
site_author: James Leffler
site_url: https://jsleffler.github.io/data-platform-tutorial
remote_branch: main
nav:
  - Home: README.md
  - Timeline: timeline.md
  - 'Getting Started':
    - 'Setup': 'getting-started/index.md'
    - 'Terraform': 'getting-started/terraform.md'
    - 'Github Actions': 'getting-started/github-actions.md'
theme:
  name: readthedocs
repo_url: https://github.com/jsleffler/data-platform-tutorial
edit_uri: edit/main/docs/
copyright: (c) James Leffler
